/**
 * IntelliStyle Api
 * IntelliStyle Api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: crusher83@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GarmentItem {
    id: string;
    productID: number;
    url: string;
    gender: string;
    description: string;
    image_urls: Array<string>;
    title: string;
    brand: string;
    price: number;
    currency: string;
    stock: number;
}
